"""add_projected_annual_sales_to_leases

Revision ID: 370a1b263778
Revises: 2c28002c64b2
Create Date: 2026-02-28 00:15:16.337865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '370a1b263778'
down_revision: Union[str, None] = '2c28002c64b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leases', sa.Column('projected_annual_sales_per_sf', sa.Numeric(precision=18, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leases', 'projected_annual_sales_per_sf')
    # ### end Alembic commands ###
