"""add_base_year_stop_amount_to_leases

Revision ID: e3bc24a08a92
Revises: 370a1b263778
Create Date: 2026-02-28 09:03:11.576759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3bc24a08a92'
down_revision: Union[str, None] = '370a1b263778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leases', sa.Column('base_year_stop_amount', sa.Numeric(precision=18, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leases', 'base_year_stop_amount')
    # ### end Alembic commands ###
